### ISSUE TITLE
problem with converted caQtDM screen

### ISSUE THREAD

**Issue by prjemian** [epics-modules/vac#1]
while setting up caQtDM screens for 7-BM, found this to be a problem:
- /APSshare/epics/synApps_5_7/support/vac-1-4-1/vacApp/op/ui/Pump.ui, macro: P=7bma1:,PUMP=IP01
- /APSshare/epics/synApps_5_8/support/vac-1-5-1/vacApp/op/ui/Pump.ui, macro: P=7bma1:,PUMP=IP01
- related display widget hidden by SP1 & SP2
- widen this entire column in the .adl file
- reconvert to various formats
- copy revised .ui file to /APSshare

**Comment by keenanlang** [comment]
Fixed in latest commit.
